# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2735779d18dc553ad2096e71fb4c365f617f9c08c2cafac5067ea0899c412e96c519f4369295cb21cce57520f3958bb1bdc70da0097521968df0559c256d894a

test:
  secret_key_base: 8a4eb3ce51cf3df10df0b7c8e223933b956f1f3174a06077d9733836d44f4d613ba9922de5c582ab0a61c37f0b664b129b8411a67f3d9faca82b5b3491e3d815

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
